name: Run Maven Tests

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Maven tests and capture output
        run: |
          mvn test | tee mvn-output.txt

      - name: Extract test failure line
        id: extract_error
        run: |
          error_line=$(grep -i "Error:  Tests run:" mvn-output.txt || echo "No test error found")
          echo "error_line=$error_line" >> $GITHUB_OUTPUT

      - name: Send to Google Chat
        if: ${{ steps.extract_error.outputs.error_line != 'No test error found' }}
        run: |
          curl -X POST \
            -H 'Content-Type: application/json' \
            -d "{\"text\": \"${{ steps.extract_error.outputs.error_line }}\"}" \
            "https://chat.googleapis.com/v1/spaces/AAAA0q_7a84/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=2sgTj39blKJrS_pAKTiHPxXi08Z-LG0lHmma4I"
