name: Run Maven Tests and Notify Google Chat

on:
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Install Playwright browser dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-4-1 \
            libgraphene-1.0-0 \
            libwoff1 \
            libvpx9 \
            libevent-2.1-7 \
            libopus0 \
            libgstreamer1.0-0 \
            libgstreamer-plugins-base1.0-0 \
            libflite1 \
            libavif16 \
            libharfbuzz-icu0 \
            libsecret-1-0 \
            libhyphen0 \
            libmanette-0.2-0 \
            libgles2 \
            libx264-dev

      - name: Run Maven tests and capture output
        id: run_tests
        run: |
          set +e
          mvn test -DsuiteXmlFile=suite/DcmAdminEnums.xml -DtestFailureIgnore=false | tee mvn-output.txt
          echo "exit_code=${PIPESTATUS[0]}" >> $GITHUB_OUTPUT
          set -e

      - name: Extract test error line (if any)
        id: extract_error
        run: |
          error_line=$(grep -i "Error:  Tests run:" mvn-output.txt || echo "")
          echo "error_line=${error_line}" >> $GITHUB_OUTPUT

      - name: Send message to Google Chat
        run: |
          if [ "${{ steps.run_tests.outputs.exit_code }}" -eq 0 ]; then
            message="✅ Maven tests passed successfully in ${{ github.repository }} on branch ${{ github.ref_name }}."
          else
            message="❌ Maven tests failed in ${{ github.repository }} on branch ${{ github.ref_name }}.\nError Summary: ${{ steps.extract_error.outputs.error_line }}"
          fi

          curl -X POST \
            -H 'Content-Type: application/json' \
            -d "{\"text\": \"$message\"}" \
            "https://chat.googleapis.com/v1/spaces/AAAA0q_7a84/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=2sgTj39vsGjHblKJrS_pAKTiHPxXi08Z-LG0lHmma4I"

      - name: Get latest file in test-output/Reports
        id: get_latest_report
        run: |
          latest_file=$(ls -t test-output/Reports/* | head -n1)
          echo "latest_file=$latest_file" >> $GITHUB_OUTPUT

      - name: Upload latest report file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: latest-report
          path: ${{ steps.get_latest_report.outputs.latest_file }}
